// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:064cb78d-c500-4af1-b5b5-e0a6ef2c9fa7',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '5411779b26b149018fd4e870469c22a3',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '75de70f1-9db4-4674-8460-32196d5b9adb',
    'aws_project_name': 'potluck-enduser',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'potluckenduser-mobilehub-416787849',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'potluckenduser-userfiles-mobilehub-416787849',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_nIhH8qBkt',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '4fjeafek2546j7lps20sj7ma3u',
}

export default awsmobile;
